title: Predictive Analytics on Healthcare Management Dataset using ML Algorithms
description: Streamlining hospital efficiencies through accurate prediction of patient length-of-stay
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
