title: Predictive Analytics on Healthcare Management Dataset
description: Streamlining hospital efficiencies through accurate prediction of patient length-of-stay using ML Algorithms
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
